apiVersion: v1
kind: Pod
metadata:
  name: kube-app-manual
spec:
  containers:
    - image: kube-app
      name: kube-app
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          protocol: TCP
