apiVersion: v1
kind: Service
metadata:
  name: kube-app-nodeport
spec:
  type: NodePort # type
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123 # node port
  selector:
    app: kube-app
