apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-app
spec:
  replicas: 3
  selector:
    app: kube-app
  template:
    metadata:
      labels:
        app: kube-app
    spec:
      containers:
        - image: kube-app
          name: kube-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
